version: '3.7'
services:
    socks5:
      build: .
      image: 'zhuguojun6/socks5:1.0.1'
      container_name: "socks5"
      restart: unless-stopped
      privileged: true
      hostname: 'socks5'

      environment:
        TZ: 'Asia/Shanghai'
        SSH_HOSTUSER: user
        SSH_HOSTNAME: host 
        SSH_HOSTPORT: 22
        PROXY_HOSTPORT: 10086
      deploy:
        resources:
          limits:
            memory: 512M
            cpus: 1
      ports:
        - '10086:10086'

      volumes:
        - ./private_keys/id_rsa:/id_rsa

